WITH 
 Base AS (SELECT * FROM MyRawData)
-- BX as (SELECT *,z=rand(),x=ABS(CHECKSUM(NewId())) % 13424  FROM STRING_SPLIT(replicate(', ',100)+ 'Lorem ipsum dolor sit amet.', ','))
-- --learned the random by row thing here:
-- --https://stackoverflow.com/questions/1045138/how-do-i-generate-a-random-number-for-each-row-in-a-t-sql-select
--,
-- B0 AS (
-- SELECT 
--  *
--  ,HitDateTimeProper   = DATEADD(hh,-6,lk.HitDateTime)
--  FROM LogKristi lk 
--  ) 
--,B1 AS (
-- SELECT
--  *
--  ,HitYear      = YEAR(HitDateTimeProper) 
--  ,HitYYYYMM     = Year(HitDateTimeProper)*100 + Month(HitDateTimeProper)
--  ,HitMonthName = UPPER(SUBSTRING(DATENAME(MONTH,HitDateTimeProper),1,3))
--  FROM B0 lk 
--  ) --correcting for the region the trail exists on.  Could choose to automate this if we had a log file from various trails around the world.. would need a trailID tho...
--,BASE AS (
-- SELECT 
--   lk.ID
--  ,lk.IP
--  ,URL           = REPLACE(lk.URL,'Kristi/','')
--  ,HitDateTime   = HitDateTimeProper --DATEADD(hh,-6,lk.HitDateTime) --correcting for the region the trail exists on.  Could choose to automate this if we had a log file from various trails around the world.. would need a trailID tho...
--  ,HitYear       --= Year(HitDateTimeProper)
--  ,HitMonth      = Month(HitDateTimeProper)
--  ,HitYYYYMM     --= Year(HitDateTimeProper)*100 + Month(HitDateTimeProper)
--  ,HitYYYYMMDD   = (Year(HitDateTimeProper)*100 + Month(HitDateTimeProper))*100 + DAY(HitDateTimeProper)
--  ,CURRMON       = CASE WHEN HitYear = YEAR(GETDATE()) THEN 'CURR' + HitMonthName WHEN HitYear = YEAR(GETDATE())-1 THEN 'PREV' + HitMonthName ELSE CONCAT('',HitYYYYMM) END 
--  ,lk.CookieID
--  ,CookieIDshort = CONCAT(SUBSTRING(lk.CookieID,1,4),'..',SUBSTRING(lk.CookieID,33,14))
--  ,Logic01       = ISNULL(lkm.Logic01,0)          -- Wether it's individuals like myself that "don't count" for testing purposes and would mess up the stats..
--  ,cip.CookiePrime
--  ,VisitorAlias  = CASE WHEN lkm.Logic01 = 1 THEN lkm.Tag1 ELSE pw.word END
--  --,UserDayHit    = CONCAT(CookiePrimer,(Year(HitDateTimeProper)*100 + Month(HitDateTimeProper))*100 + DAY(HitDateTimeProper))
-- FROM B1 lk --LogKristi lk
-- LEFT JOIN LogKristiMeta lkm ON lk.CookieID = lkm.CookieID 
-- LEFT JOIN CookieIDPrime cip ON cip.CookieID = lk.CookieID
-- LEFT JOIN PronounceableWords pw ON pw.id = cip.cookieprime
--)
----,base2 as ( SELECT  URL,HitDateTime,ID=concat(SUBSTRING(CookieID,1,4),'..',SUBSTRING(CookieID,33,14)) FROM base1 n WHERE n.Logic01=0 )
----,base  AS (SELECT * 
--,BaseProper AS ( SELECT * FROM BASE WHERE LOGIC01 = 0)
----SELECT * FROM BASEPROPER ORDER BY ID DESC
----,HitCountVisitorsYYYYMMDD AS (SELECT HitYYYYMMDD, HitYYYYMM, HITYear, VisitorAlias, Hits=COUNT(*), DistinctStops=COUNT(DISTINCT URL), DistinctVisit=COUNT(DISTINCT CookiePrime) FROM BASEPROPER GROUP BY HITYear, HITYYYYMM, HITYYYYMMDD,VisitorAlias)
--,HitCountVisitorsYYYYMMDD AS (SELECT HitYYYYMMDD, CURRMON, HITYear, VisitorAlias, Hits=COUNT(*), DistinctStops=COUNT(DISTINCT URL), DistinctVisit=COUNT(DISTINCT CookiePrime) FROM BASEPROPER GROUP BY HITYear, CURRMON, HITYYYYMMDD,VisitorAlias)
--,HitCountVisitorsYYYYMM AS (
-- SELECT 
--  CURRMON --HitYYYYMM = CASE WHEN HITYEAR = YEAR(GETDATE()) THEN 'CURR' + SUBSTRING(CONCAT('',HitYYYYMM),4,2) WHEN HitYear = YEAR(GETDATE())-1 THEN 'PREV' + SUBSTRING(CONCAT('',HitYYYYMM),4,2) ELSE CONCAT('',HitYYYYMM) END
-- ,VisitorAlias
-- ,Visits=COUNT(DistinctVisit)
-- ,DaysVisited=COUNT(DISTINCT HITYYYYMMDD)
-- ,DistinctStops=SUM(DistinctStops)
-- ,Hits=SUM(Hits)
-- FROM HitCountVisitorsYYYYMMDD 
-- GROUP BY CURRMON, VisitorAlias)
----select *,x=case when VisitorAlias in ('Clark','eikwoopyae') Then '<<<<<<<<<<' else '' end from BaseProper order by id desc--eikwoopyae order by id desc
----,HitCounts AS (SELECT HitYYYYMM, Hits=COUNT(*), DistinctVisits(DISTINCT UserDayHit), DistinctVisitors=COUNT(DISTINCT CookiePrime) FROM BASEPROPER GROUP BY HITYYYYMM)
--,ByYearVisitors AS (
--SELECT  VisitorAlias
--,[PREVJAN] AS PREVJAN
--,[PREVFEB] AS PREVFEB
--,[PREVMAR] AS PREVMAR
--,[PREVAPR] AS PREVAPR
--,[PREVMAY] AS PREVMAY
--,[PREVJUN] AS PREVJUN
--,[PREVJUL] AS PREVJUL
--,[PREVAUG] AS PREVAUG
--,[PREVSEP] AS PREVSEP
--,[PREVOCT] AS PREVOCT
--,[PREVNOV] AS PREVNOV
--,[PREVDEC] AS PREVDEC
--,[CURRJAN] AS CURRJAN
--,[CURRFEB] AS CURRFEB
--,[CURRMAR] AS CURRMAR
--,[CURRAPR] AS CURRAPR
--,[CURRMAY] AS CURRMAY
--,[CURRJUN] AS CURRJUN
--,[CURRJUL] AS CURRJUL
--,[CURRAUG] AS CURRAUG
--,[CURRSEP] AS CURRSEP
--,[CURROCT] AS CURROCT
--,[CURRNOV] AS CURRNOV
--,[CURRDEC] AS CURRDEC
--FROM ( 
--SELECT CURRMON,Visits,VisitorAlias FROM HitCountVisitorsYYYYMM 
--) AS MYDATA
--PIVOT
-- (
-- SUM(Visits)
-- FOR CURRMON IN (
-- [PREVJAN]
--,[PREVFEB]
--,[PREVMAR]
--,[PREVAPR]
--,[PREVMAY]
--,[PREVJUN]
--,[PREVJUL]
--,[PREVAUG]
--,[PREVSEP]
--,[PREVOCT]
--,[PREVNOV]
--,[PREVDEC]
--,[CURRJAN]
--,[CURRFEB]
--,[CURRMAR]
--,[CURRAPR]
--,[CURRMAY]
--,[CURRJUN]
--,[CURRJUL]
--,[CURRAUG]
--,[CURRSEP]
--,[CURROCT]
--,[CURRNOV]
--,[CURRDEC]
--)) AS MYPIVOT 
----ORDER BY SUM(VISITS)
--) 
--, ByYearVisitorsWithSummary AS (
--SELECT * FROM ByYearVisitors
--UNION ALL	SELECT '--ALL--'
--,SUM(PREVJAN)
--,SUM(PREVFEB)
--,SUM(PREVMAR)
--,SUM(PREVAPR)
--,SUM(PREVMAY)
--,SUM(PREVJUN)
--,SUM(PREVJUL)
--,SUM(PREVAUG)
--,SUM(PREVSEP)
--,SUM(PREVOCT)
--,SUM(PREVNOV)
--,SUM(PREVDEC)
--,SUM(CURRJAN)
--,SUM(CURRFEB)
--,SUM(CURRMAR)
--,SUM(CURRAPR)
--,SUM(CURRMAY)
--,SUM(CURRJUN)
--,SUM(CURRJUL)
--,SUM(CURRAUG)
--,SUM(CURRSEP)
--,SUM(CURROCT)
--,SUM(CURRNOV)
--,SUM(CURRDEC)
--FROM ByYearVisitors
--)
----SELECT * FROM ByYearVisitorsWithSummary
----SELECT * FROM Hitcounts ORDER BY HITYYYYMM DESC
----SELECT * FROM HitCountVisitorsYYYYMMDD ORDER BY HITYYYYMMDD DESC
----SELECT TheDay=HitYYYYMMDD,VisitorAlias,DistinctStops FROM HitCountVisitorsYYYYMMDD ORDER BY HITYYYYMMDD DESC
----SELECT * FROM HitCountVisitorsYYYYMM ORDER BY VisitorAlias, CURRMON DESC
----select *,xx = case when  ip in ('207.47.130.111') or VisitorAlias in ('Clark') then '<<<<<<<<<' else '' end from BaseProper  order by id desc
----select *,xx = case when  cookieid in (
---- '00797E4F-846B-47E4-B7CA-108F41FEE1B2'
----,'0B800B63-C175-47F8-B9DA-34B4219E5175'
----,'6407B884-B263-4042-84E3-CF16A69FBE5F'
----,'6EBC5E72-A97E-4E60-AEA4-1E39C86DE0D7'
----,'769A2CFB-D88F-4F6D-B7DF-DDE2966D2D50'
----,'9293FB2F-88EC-4C1A-BEC7-72B9DED09ED5'
----,'ADDF8F83-5905-49C8-9197-941E1008AD7E'
----,'BB2684B5-3F47-4791-BC30-84B70676A2BC'
----,'BC51276C-6F07-4B6D-991B-0932B3B01134'
----,'C9915031-21B4-4BF6-B204-D2F2D317A1E7'
----,'D33C171E-1034-46D5-A86F-DC609F0AA499'
----,'DCD33C52-AD89-4558-BE32-6961178050FE') then '!!!!!!!!' when 
----ip in ('207.47.130.111') or VisitorAlias in ('Clark') then '<<<<<<<<<' else '' end from BaseProper  order by id desc

----select distinct cookieID from baseproper where  ip in ('207.47.130.111') and not  VisitorAlias in ('Clark') 
----select * from baseproper order by id desc
----select * from base order by id desc
----select * from LogKristi order by id desc
select * from base